[book]
title = "Grzegorz Krasoń"
authors = ["Grzegorz Krasoń"]
language = "en"
multilingual = false
src = "src"

[output.html]
no-section-label = true

[output.html.search]
enable = false

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 1

[preprocessor.emoji]
renderer = ["html"]
